# Generated by Django 3.2.4 on 2021-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_createdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdate',
        ),
        migrations.AlterField(
            model_name='user',
            name='createdatetime',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
